apiVersion: apps/v1
kind: Deployment
metadata:
  name: sponsors-service
  namespace: elearning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sponsors-service
  template:
    metadata:
      labels:
        app: sponsors-service
    spec:
      containers:
      - name: sponsors-service
        image: elearning/sponsors-service:latest
        ports:
        - containerPort: 8021
