version: '3.8'

services:
  notifications-service:
    build: .
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/notifications_service_db
      - REDIS_URL=redis://localhost:6379
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8007
