version: '3.8'

services:
  quizzes-service:
    build: .
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/quizzes_service_db
      - REDIS_URL=redis://localhost:6379
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8004
