apiVersion: v1
kind: Service
metadata:
  name: gamification-service
  namespace: elearning
spec:
  type: ClusterIP
  ports:
  - port: 8009
    targetPort: 8009
  selector:
    app: gamification-service
