apiVersion: v1
kind: Service
metadata:
  name: communications-service
  namespace: elearning
spec:
  type: ClusterIP
  ports:
  - port: 8012
    targetPort: 8012
  selector:
    app: communications-service
